# Generated by Django 5.2.8 on 2025-11-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketFinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
    ]
