# Generated by Django 4.2.26 on 2025-11-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketFinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_ticket',
            name='data',
        ),
        migrations.AddField(
            model_name='save_ticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
