# Generated by Django 4.2.26 on 2025-11-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketFinder', '0002_remove_save_ticket_data_save_ticket_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_ticket',
            name='event_ConvertedDate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='save_ticket',
            name='event_ConvertedTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='save_ticket',
            name='event_imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='save_ticket',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='save_ticket',
            name='event_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='save_ticket',
            name='theater_address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='save_ticket',
            name='theater_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='save_ticket',
            name='theater_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
