# Generated by Django 5.2.8 on 2025-12-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketFinder', '0002_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
