# Generated by Django 5.2.8 on 2025-12-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketFinder', '0003_notes_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedtickets',
            old_name='event_ConvertedDate',
            new_name='event_Date',
        ),
        migrations.RenameField(
            model_name='savedtickets',
            old_name='event_ConvertedTime',
            new_name='event_Time',
        ),
    ]
