# Generated by Django 4.2.26 on 2025-11-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketFinder', '0003_save_ticket_event_converteddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_ticket',
            name='ticket_id',
        ),
    ]
